/*  =========================================================================
    shelf - Represents a Shelf (containing a set of Books)

    Copyright (c) the Contributors as noted in the AUTHORS file.       
    This file is part of CZMQ, the high-level C binding for 0MQ:       
    http://czmq.zeromq.org.                                            
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           
    =========================================================================
*/

#ifndef __BOOK_H_INCLUDED__
#define __BOOK_H_INCLUDED__

#ifdef __cplusplus
extern "C" {
#endif


//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT!
//  @warning Please edit the model at "api/shelf.xml" to make changes.
//  @interface
//  Create a new Book with the given title and author.
OBOOKS_EXPORT book_t *
    book_new (const char *id, const char *author, const char *title);

OBOOKS_EXPORT char*
    book_get_title (book_t *self);

OBOOKS_EXPORT char*
    book_get_author (book_t *self);

//  Destroy the book.
OBOOKS_EXPORT void
    book_destroy (book_t **self_p);

//  
OBOOKS_EXPORT int
    book_count_books (book_t *self);

OBOOKS_EXPORT int
    book_test (bool verbose);

OBOOKS_EXPORT void
    book_print (book_t *self);

//  @end

#ifdef __cplusplus
}
#endif

#endif
