//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT!
//  @warning Please edit the model at "api/shelf.xml" to make changes.
//  @interface
//  Create a new Book with the given title and author.
OBOOKS_EXPORT book_t *
    book_new (const char *title, const char *author, zpgutil_session *session);

//  Destroy the book.
OBOOKS_EXPORT void
    book_destroy (book_t **self_p);

//  
OBOOKS_EXPORT int
    book_count_books (book_t *self);
//  @end
