/*  =========================================================================
    obooks - OBOOKS wrapper

    Copyright (c) the Contributors as noted in the AUTHORS file.       
    This file is part of CZMQ, the high-level C binding for 0MQ:       
    http://czmq.zeromq.org.                                            
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef __obooks_library_H_INCLUDED__
#define __obooks_library_H_INCLUDED__

//  External dependencies
#include <zmq.h>
#include <czmq.h>
#include <pq.h>
#include <zpgutil.h>

//  OBOOKS version macros for compile-time API detection

#define OBOOKS_VERSION_MAJOR 1
#define OBOOKS_VERSION_MINOR 0
#define OBOOKS_VERSION_PATCH 0

#define OBOOKS_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define OBOOKS_VERSION \
    OBOOKS_MAKE_VERSION(OBOOKS_VERSION_MAJOR, OBOOKS_VERSION_MINOR, OBOOKS_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined LIBOBOOKS_STATIC
#       define OBOOKS_EXPORT
#   elif defined LIBOBOOKS_EXPORTS
#       define OBOOKS_EXPORT __declspec(dllexport)
#   else
#       define OBOOKS_EXPORT __declspec(dllimport)
#   endif
#else
#   define OBOOKS_EXPORT
#endif

//  Opaque class structures to allow forward references
typedef struct _book_t book_t;
#define BOOK_T_DEFINED
typedef struct _shelf_t shelf_t;
#define SHELF_T_DEFINED


//  Public API classes
#include "book.h"
#include "shelf.h"

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
