/*  =========================================================================
    shelf - Represents a Shelf (containing a set of Books)

    Copyright (c) the Contributors as noted in the AUTHORS file.       
    This file is part of CZMQ, the high-level C binding for 0MQ:       
    http://czmq.zeromq.org.                                            
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           
    =========================================================================
*/

#ifndef __SHELF_H_INCLUDED__
#define __SHELF_H_INCLUDED__

#ifdef __cplusplus
extern "C" {
#endif


//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT!
//  @warning Please edit the model at "api/shelf.xml" to make changes.
//  @interface
//  Create a new Book with the given title and author.
OBOOKS_EXPORT shelf_t *
    shelf_new (zpgutil_session_t *session);

//  Destroy the shelf.
OBOOKS_EXPORT void
    shelf_destroy (shelf_t **self_p);

//  
OBOOKS_EXPORT int
    shelf_count_books (shelf_t *self);

OBOOKS_EXPORT void
    shelf_load_books (shelf_t *self);

OBOOKS_EXPORT book_t*
    shelf_next_book (shelf_t *self);

OBOOKS_EXPORT book_t* 
    shelf_add_book (shelf_t *self, const char* title, const char* author);

OBOOKS_EXPORT int
    shelf_test (bool verbose);

//  @end

#ifdef __cplusplus
}
#endif

#endif
